root = "."
tmp_dir = "tmp"

[build]
pre_cmd = ["templ generate", "npm run tailwind:build"]
cmd = "go build -o ./tmp/main ."
delay = 1000
exclude_dir = ["assets", "tmp"]
exclude_file = []
exclude_regex = [".*_templ.go"]
exclude_unchanged = false
follow_symlink = false
full_bin = "./tmp/main"
include_dir = []
include_ext = ["go", "tpl", "tmpl", "templ", "html"]
kill_delay = "0s"
log = "build-errors.log"
send_interrupt = false
stop_on_error = true

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
time = false

[misc]
clean_on_exit = false
