root = "."
tmp_dir = "tmp"

[build]
pre_cmd = ["templ generate", "npm run tailwind:build"]
cmd = "go build -o ./tmp/main ."
full_bin = "./tmp/main"
delay = 1000
exclude_dir = ["assets", "tmp", "node_modules", "bin"]
exclude_regex = [".*_templ.go"]
exclude_unchanged = false
follow_symlink = false
include_ext = ["go", "tpl", "tmpl", "templ", "html"]
send_interrupt = true
stop_on_error = true
kill_delay = 5000

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
time = false

[misc]
clean_on_exit = false
