version: "3"

tasks:
  templ-gen:
    cmd: templ generate

  tailwind-watch:
    cmd: npm run tailwind:watch

  tailwind-build:
    cmd: npm run tailwind:build

  serve:
    deps: [tailwind-watch, run]

  build-image:
    cmd: docker build . --tag=delphinium:latest -f ./Dockerfile.production
  
  tag-image:
    cmd: docker tag delphinium europe-west1-docker.pkg.dev/proj-delphinium/proj-delphinium/delphinium

  push-image:
    cmd: docker push europe-west1-docker.pkg.dev/proj-delphinium/proj-delphinium/delphinium

  build-and-push-image:
    cmds:
      - task: build-image
      - task: tag-image
      - task: push-image

  deploy:
    cmd: gcloud run deploy main --image europe-west1-docker.pkg.dev/proj-delphinium/proj-delphinium/delphinium