version: "3"

dotenv: ['.env']

env:
  ARTIFACT_URL: '{{ .GCP_REGION }}-docker.pkg.dev/{{ .GCP_PROJECT_ID }}/{{ .GCP_ARTIFACT_REGISTRY_ID }}/{{ .GCP_ARTIFACT_NAME }}'

tasks:
  templ-gen:
    cmd: templ generate

  tailwind-watch:
    cmd: npm run tailwind:watch

  tailwind-build:
    cmd: npm run tailwind:build

  serve:
    deps: [tailwind-watch, run]

  build-image:
    cmd: docker build . --tag=$GCP_ARTIFACT_NAME:latest -f ./Dockerfile.production
  
  tag-image:
    cmd: docker tag delphinium $ARTIFACT_URL

  push-image:
    cmd: docker push $ARTIFACT_URL

  build-and-push-image:
    cmds:
      - task: build-image
      - task: tag-image
      - task: push-image

  deploy:
    cmd: gcloud run deploy main --image $ARTIFACT_URL
    